# most of the properties can be changed in the gradle.properties
name: '${plugin_name}'
version: '${version}'
main: be.raft.legions.Legions
api-version: '${api_version}'
authors: [ Raft ]
description: '${plugin_description}'
website: '${plugin_website}'
commands:
  legion:
    description: Legions main command
    usage: /<command>